name: Metrics
on:
  schedule:
    - cron: "0 */12 * * *"   # 12시간마다
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # 토큰: private 포함하려면 secrets.METRICS_TOKEN, public만이면 ${{ github.token }}
          token: ${{ secrets.METRICS_TOKEN || github.token }}
          user: Youtak2
          template: classic
          filename: metrics.svg
          config_timezone: Asia/Seoul

          # 기본 블록
          base: header, activity, community, repositories, metadata

          # 핀/대표 레포
          plugin_repositories: yes
          plugin_repositories_featured: yes
          plugin_repositories_pinned: 6

          # 최근 활동
          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_activity_timestamps: true

          # 언어/커밋 캘린더
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # (옵션) 업적
          plugin_achievements: yes
          plugin_achievements_threshold: C
